//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using test01;
using UnityEngine;
namespace HoxFixCode
{
    public class TestClass
    {
        public int name = 213;
        public int v2 = 33;
        public TestClass()
        {
        }

        public static void Test1()
        {
            Interface.Test1();
        }
        Transform transform = null;
        public void Test2()
        {
            v2++;
            Interface.Test2();
            if (transform == null)
            {
                Console.WriteLine("fuu");
                GameObject go = new GameObject();
                transform = go.transform;
            }
            //Vector3 vector3 = new Vector3(0, 0, 0);
            //transform.localPosition = vector3;
        }

        public void Test3(int abc, string def)
        {
            Console.WriteLine(def + "=" + abc);
            Interface.SetMyType(CreateMyI());
            Interface.UseType();
        }
        public static Interface.IMyType CreateMyI()
        {
            return new myi();
        }
        public class myi : Interface.IMyType
        {
            string name = "";
            public string GetName()
            {
                return name;
            }

            public string GetDesc()
            {
                return "crossbind very cool.";
            }
            public void SetName(string name)
            {
                this.name = name;
            }
        }
    }
}

